name: CI

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'OS to run on'
        required: false
        type: choice
        options:
          - all
          - ubuntu-latest
          - macos-latest
        default: 'all'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npx biome ci src/

  e2e:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: >-
          ${{
            github.event_name == 'push'
              && fromJson('["ubuntu-latest","macos-latest"]')
            || github.event_name == 'workflow_dispatch' && github.event.inputs.os == 'all'
              && fromJson('["ubuntu-latest","macos-latest"]')
            || github.event_name == 'workflow_dispatch'
              && fromJson(format('["{0}"]', github.event.inputs.os))
            || fromJson('["ubuntu-latest"]')
          }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npx playwright install chromium --with-deps
      - run: npm run test-ci
